export const carModels: Record<string, string[]> = {
  Toyota: [
    'Corolla',
    'Camry',
    'RAV4',
    'Land Cruiser',
    'Hilux',
    'Prius',
    'Yaris',
    'Supra',
  ],
  BMW: ['3 Series', '5 Series', '7 Series', 'X1', 'X3', 'X5', 'i4', 'M4'],
  Mercedes: [
    'A-Class',
    'C-Class',
    'E-Class',
    'S-Class',
    'GLE',
    'GLC',
    'AMG GT',
    'EQS',
  ],
  Audi: ['A3', 'A4', 'A6', 'A8', 'Q3', 'Q5', 'Q7', 'e-tron GT'],
  Volkswagen: [
    'Golf',
    'Passat',
    'Tiguan',
    'Touareg',
    'Polo',
    'Arteon',
    'Jetta',
    'T-Roc',
  ],
  Ford: [
    'Focus',
    'Mustang',
    'Explorer',
    'F-150',
    'Edge',
    'Escape',
    'Maverick',
    'Bronco',
  ],
  Chevrolet: [
    'Malibu',
    'Impala',
    'Camaro',
    'Corvette',
    'Tahoe',
    'Suburban',
    'Equinox',
    'Silverado',
  ],
  Hyundai: [
    'Elantra',
    'Sonata',
    'Tucson',
    'Santa Fe',
    'Palisade',
    'Ioniq 5',
    'Kona',
    'Staria',
  ],
  Kia: [
    'Rio',
    'Sportage',
    'Sorento',
    'Carnival',
    'EV6',
    'Seltos',
    'Cerato',
    'K5',
  ],
  Nissan: [
    'Sentra',
    'Altima',
    'Maxima',
    'X-Trail',
    'Qashqai',
    'Patrol',
    'GT-R',
    'Leaf',
  ],
  Mazda: [
    'CX-3',
    'CX-5',
    'CX-9',
    'MX-5 Miata',
    'RX-8',
    'BT-50',
  ],
  Subaru: [
    'Impreza',
    'WRX',
    'Outback',
    'Forester',
    'Legacy',
    'Crosstrek',
    'BRZ',
    'Ascent',
  ],
  Honda: [
    'Civic',
    'Accord',
    'CR-V',
    'HR-V',
    'Pilot',
    'Odyssey',
    'Ridgeline',
    'Brio',
  ],
  Porsche: [
    '911',
    'Cayenne',
    'Macan',
    'Panamera',
    'Taycan',
    '718 Boxster',
    '718 Cayman',
    'Carrera GT',
  ],
  Lexus: ['IS', 'ES', 'GS', 'LS', 'NX', 'RX', 'GX', 'LX'],
};
